baseURL = "http://hugo-test-static-website.s3-website-eu-west-1.amazonaws.com"
2 languageCode = "en-us"
3 title = "My New Hugo Sit via AWS Cloud9"
4 theme = "ananke"
5
6 [[deployment.targets]]
7 # An arbitrary name for this target.
8 name = "awsbucket"
9 URL = "s3://hugo-test-static-website/?region=eu-west-1" #your bucket here